### ISSUE TITLE
Does this repository can also train the multi agent MLAgents examples like tennis

### ISSUE THREAD

**Issue by Usmaniatech** [YuhangSong/Arena-Baselines#2]
Does this repository can also train the multi agent MLAgents examples like tennis ?

**Comment by YuhangSong** [comment]
Yes, simply run
```
CUDA_VISIBLE_DEVICES=0 python main.py --mode train --env-name Tennis-2T1P-v1-Discrete --obs-type visual --num-frame-stack 4 --recurrent-brain --normalize-obs --trainer ppo --use-gae --lr 2.5e-4 --value-loss-coef 0.5 --ppo-epoch 4 --num-processes 16 --num-steps 1024 --num-mini-batch 16 --use-linear-lr-decay --entropy-coef 0.01 --clip-param 0.1 --num-env-steps 100000000 --reload-playing-agents-principle OpenAIFive --vis --vis-interval 1 --log-interval 1 --num-eval-episodes 10 --arena-start-index 31569 --aux 0
```

You will get a self-play PPO training on the game Tennis with 2 players, of discrete action space.

The binary compiled game is already in the repo, so run above command is all you need.

However, you can plug in your own version of Tennis game built from Unity ML-Agents, the Arena-Baselines is never designed just for games built from ourselves and does not apply any restrict on the unity side (as long as the multiple agents in the game are of the same action space, i.e. symmetrical multi-agent settings, we will support Asymmetrical multi-agent settings in a future update).

But it is recommended to built your multi-agent game with Arena-BuildingToolkit, with many features you may find super handy and your built game is extensible to more multi-agent paradigms.

Take a look at:

- [Arena-BuildingToolkit](https://github.com/YuhangSong/Arena-BuildingToolkit)

- [tutorials-building-toolkit](https://sites.google.com/view/arena-unity/home/tutorials-building-toolkit)

Also, there is already a Tennis game in Arena-BuildingToolkit, start from there you should find it very easy to build your customized games.

**Comment by Usmaniatech** [comment]
Tennis is just a test example. After testing it on tennis I want to train a different custom environment built in unity. Scene is already built So, I can't built it on arena baselines. I want to train it on DQN and ddpg provided in gym unity
https://github.com/Unity-Technologies/ml-agents/tree/master/gym-unity

https://github.com/Unity-Technologies/ml-agents/issues/2292#issuecomment-513314561
Ervin suggested that it might be version issue, but I've installed the exact versions specified in repo.

Other question is ML Agents 0.8.2 is installing 0.4.2 version of gym unity, Earlier in previous versions, It was using 0.10.9, why have u degraded the versions ?? @YuhangSong

**Comment by YuhangSong** [comment]
Bad news is that we do not have DQN and ddpg implemented, instead we implement more popular algorithms like PPO, A2C, ARTC, etc.

I am not experienced with gym unity, so I am afraid I can not offer more suggestions on that. The only experience with it is that it does not support parallel training with many workers. That's why we make our own baselines that support parallel training.

But I took a look at your error, n only exists in discrete action space, while Box is used to define a continuous action space. So simply speaking, your game has continuous action space, but your agent is trying to get the discrete action space. Hope this hint helps you find the problem.

In this repo, actions space type (discrete/continuous) of a game is detected and the agent's action space is accordingly adjusted, so this repo deals with both action space without the need of extra effort.

Though haven't tested, I think the version of the gym does not make a big difference. From where I see, this repo is using all packages in the latest version, where did you see I degrade the versions?
